name: flutter_cloud_kit_example
description: Demonstrates how to use the flutter_cloud_kit plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_cloud_kit:
    path: ../

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
